# Supported funding platforms for Saran (Ocuris)

github: ["ocuris"]        # GitHub Sponsors
patreon: "ocuris"         # Patreon
open_collective: "saral"  # Open Collective
ko_fi: "ocuris"           # Ko-fi
buy_me_a_coffee: "ocuris" # Buy Me a Coffee
